# Generated by Django 4.2 on 2025-03-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Changes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('icon_class', models.CharField(max_length=50, verbose_name='کلاس آیکون')),
                ('counter_end', models.IntegerField(verbose_name='عدد نهایی')),
                ('description', models.CharField(max_length=200, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'تغییر',
                'verbose_name_plural': 'تغییرات',
            },
        ),
    ]
