# Generated by Django 4.2 on 2025-03-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changes',
            name='counter_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد نهایی'),
        ),
        migrations.AlterField(
            model_name='changes',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='changes',
            name='icon_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کلاس آیکون'),
        ),
        migrations.AlterField(
            model_name='changes',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان'),
        ),
    ]
