# Generated by Django 4.2 on 2025-03-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_changes_counter_end_alter_changes_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changes',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='changes',
            name='icon_file',
            field=models.FileField(blank=True, null=True, upload_to='icons/', verbose_name='فایل آیکون'),
        ),
    ]
