# Generated by Django 4.2 on 2025-03-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('percentage', models.IntegerField(help_text='عدد بین 0 تا 100', verbose_name='درصد')),
            ],
        ),
    ]
