# Generated by Django 4.2 on 2025-03-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon_class', models.CharField(help_text='کلاس آیکون برای استفاده در template', max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
