# Generated by Django 4.2 on 2025-03-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='services/default0.jpg', upload_to='services'),
        ),
    ]
