# Generated by Django 4.2 on 2025-03-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_remove_service_icon_class_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_class',
            field=models.CharField(default='', help_text='کلاس آیکون برای استفاده در template', max_length=100),
            preserve_default=False,
        ),
    ]
