# Generated by Django 4.2 on 2025-03-23 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_service_icon_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon_class',
        ),
    ]
