# Generated by Django 4.2 on 2025-03-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(default='test', max_length=100)),
                ('TITLE', models.CharField(default='test', max_length=100)),
                ('SUBJECT', models.CharField(default='test', max_length=100)),
                ('FIRST_TEXT', models.CharField(default='test', max_length=100)),
                ('SECOND_TEXT', models.CharField(default='test', max_length=100)),
                ('THIRD_TEXT', models.CharField(default='test', max_length=100)),
                ('DESCRIPTION', models.TextField(default='test')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
