# Generated by Django 4.2 on 2025-03-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='DESCRIPTION',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='FIRST_TEXT',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='SECOND_TEXT',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='SUBJECT',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='THIRD_TEXT',
        ),
    ]
