# Generated by Django 4.2 on 2025-03-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_remove_resume_description_remove_resume_first_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='DESCRIPTION',
            field=models.TextField(default='test'),
        ),
        migrations.AddField(
            model_name='resume',
            name='FIRST_TEXT',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='SECOND_TEXT',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='SUBJECT',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='THIRD_TEXT',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
