# Generated by Django 4.2 on 2025-03-03 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
