# Generated by Django 4.2 on 2025-03-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_delete_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
            },
        ),
    ]
