# Generated by Django 4.2 on 2025-03-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_contactmessage_delete_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('icon', models.CharField(max_length=100, verbose_name='آیکون')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='لینک به صفحه جزئیات')),
            ],
            options={
                'verbose_name': 'سرویس',
                'verbose_name_plural': 'سرویس\u200cها',
            },
        ),
    ]
