# Generated by Django 4.2 on 2025-03-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(default='services/default0.jpg', upload_to=''),
        ),
    ]
