# Generated by Django 4.2 on 2025-03-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_alter_contactmessage_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
