# Generated by Django 4.2 on 2025-03-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_alter_contactmessage_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='happy_clients',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='projects_completed',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='years_experience',
        ),
        migrations.AddField(
            model_name='statistic',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
