# Generated by Django 4.2 on 2025-03-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_alter_service_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='تصویر سرویس'),
        ),
    ]
