# Generated by Django 4.2 on 2025-03-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0012_remove_service_icon_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='Default Service', null=True, upload_to='services/', verbose_name='تصویر سرویس'),
        ),
    ]
