# Generated by Django 4.2 on 2025-03-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0013_alter_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200, verbose_name='مرکز آموزشی')),
                ('degree', models.CharField(max_length=200, verbose_name='مدرک')),
                ('field_of_study', models.CharField(max_length=200, verbose_name='رشته تحصیلی')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('is_current', models.BooleanField(default=False, verbose_name='در حال حاضر')),
            ],
            options={
                'verbose_name': 'تحصیلات',
                'verbose_name_plural': 'تحصیلات',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='شرکت')),
                ('position', models.CharField(max_length=200, verbose_name='موقعیت شغلی')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('is_current', models.BooleanField(default=False, verbose_name='در حال حاضر')),
            ],
            options={
                'verbose_name': 'تجربه کاری',
                'verbose_name_plural': 'تجربه\u200cهای کاری',
            },
        ),
    ]
